spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rob2?serverTimezone=UTC
    username: root
    password: Alpaka123!@#$%

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

